### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by m-242** [bbriggs/bitbot#147]
The README and the example-config.yaml files need to be updated.

For instance, we need to explicit that the db must be put up with docker-compose, and that the db's infos must be put in the example-config.yaml as such:
```yaml
... Rest of config ...
prom: "true"
promAddr: "0.0.0.0:8080"
dbuser: "bitbot"
dbpass: "bitbot"
dbhost: "127.0.0.1"
dbport: "5432"
dbsslmode: "disable"
```
