### ISSUE TITLE
Unable to setup bitbot on local system

### ISSUE THREAD

**Issue by linkin-park** [bbriggs/bitbot#161]
Did follow the `README.md` to setup the project locally but it was quite unsuccessful.
Please update `README.md` , step by step to setup the project and run it 

Note: There is no test files to know the project was setup correctly.

I'm getting lost in the docker thing.

**Comment by m-242** [comment]
The README has been updated on the `dev` branch, but since we are not completely done with the 1.3.0 release, it's not updated on `master` yet.
Have you tried with the `dev` branche's `README` ?

**Comment by linkin-park** [comment]
Yes on dev branch `README`.

**Comment by m-242** [comment]
Do you get an error ?
Could you post the command you enter and their output ?

**Comment by linkin-park** [comment]
Sure , steps followed.

1. Setup the project on the editor [in my case vscode].
2. Ran the following command `go get github.com/bbriggs/bitbot && go install github.com/bbriggs/bitbot`
3. Ran following command `docker run --rm -it -v `pwd`/config.yaml:/app/config.yaml bbriggs/bitbot --config /app/config.yaml`
 // Error docker: Error response from daemon: invalid mode: /app/config.yaml
[PS what is config.yaml file? , its not there in my directory!, what it should contain?]
[pwd: the directory where bitbot project existed]

**Comment by m-242** [comment]
`config.yaml` is bitbot's mandatory config file.
You can `cp example-config.yaml config.yaml` and edit `config.yaml` to fit your needs.

**Comment by linkin-park** [comment]
Getting same error

**Comment by linkin-park** [comment]
okay , let me figure it out in night  by the way please update `README`.

**Comment by m-242** [comment]
I would love to, but while we don't know what how to solve the problem you are meeting, updating the README is going to be a bit difficult :)

Let me clarify the command, just in case it helps :
```shell
docker run --rm -it -v `pwd`/config.yaml:/app/config.yaml bbriggs/bitbot --config /app/config.yaml
```

+ `docker run` creates a new container

+ `--rm` indicates that the container should be removed if it already exists, this allows to auto-restart the container more easily.

+ `-it` means that the container has a terminal that is accessible, and that the output from the container is redirected to the terminal you launched the command from.

+ `-v` indicates a volume mounted into the container, here it's only a file, the config file.
It is considered located at `$(pwd)/config.yaml`, meaning whatever directory you are running the command from. It is accessible in the container at `/app/config/`.

+ `bbriggs/bitbot --config /app/config.yaml` indicates the image we are running (`bbriggs/bitbot`) and runs bitbot inside the container with the `--config /app/config.yaml` flag (see Dockerfile), meaning that we indicate to the containerized bitbot that we want it to use the config file we mounted earlier.

**Comment by linkin-park** [comment]
For this project `too many libs are downloaded` this doesn't work well for slow internet.
my  `docker-compose.yaml`
```yaml
version: "2"
services: # same as docker run
 bitbot: # bitbot
    build: .
    links: 
        - db:postgres # made relative change in code for dbHost
    # image: "bbriggs/bitbot"
    command: "--config /app/config.yaml" # ENTRYPOINT has been set
    volumes: 
        - "./config.yaml:/app/config.yaml"
    ports: 
        - "9090:8080"
    depends_on: 
        - db
 db: # postgres service
    image: postgres
```
