### ISSUE TITLE
Migrate docker image from dockerhub's registery to github's

### ISSUE THREAD

**Issue by m-242** [bbriggs/bitbot#249]

**Comment by bbriggs** [comment]
```
name: Deploy Docker

on:
  push:
    tags:
      - v*

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PAT }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          push: true # Will only build if this is not here
          tags: |
            docker.pkg.github.com/${{ github.repository }}:${{ steps.get_version.outputs.VERSION }}
            docker.pkg.github.com/${{ github.repository }}:latest
```
